# Generated by Django 3.2.23 on 2023-12-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
