# Generated by Django 3.2.23 on 2024-01-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240107_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionplan',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
